"""empty message

Revision ID: 0b4027945624
Revises: 
Create Date: 2026-01-09 15:14:01.821359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4027945624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_value', sa.Integer(), nullable=False),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autoservice_id'), 'autoservice', ['id'], unique=False)
    op.create_index(op.f('ix_autoservice_service_date'), 'autoservice', ['service_date'], unique=False)
    op.create_index(op.f('ix_autoservice_uuid'), 'autoservice', ['uuid'], unique=True)
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_payment_method_id'), 'payment_method', ['id'], unique=False)
    op.create_index(op.f('ix_payment_method_uuid'), 'payment_method', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('payment_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.Integer(), nullable=False),
    sa.Column('autoservice', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autoservice'], ['autoservice.id'], ),
    sa.ForeignKeyConstraint(['payment_method'], ['payment_method.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_value_id'), 'payment_value', ['id'], unique=False)
    op.create_index(op.f('ix_payment_value_uuid'), 'payment_value', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_value_uuid'), table_name='payment_value')
    op.drop_index(op.f('ix_payment_value_id'), table_name='payment_value')
    op.drop_table('payment_value')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_payment_method_uuid'), table_name='payment_method')
    op.drop_index(op.f('ix_payment_method_id'), table_name='payment_method')
    op.drop_table('payment_method')
    op.drop_index(op.f('ix_autoservice_uuid'), table_name='autoservice')
    op.drop_index(op.f('ix_autoservice_service_date'), table_name='autoservice')
    op.drop_index(op.f('ix_autoservice_id'), table_name='autoservice')
    op.drop_table('autoservice')
    # ### end Alembic commands ###
