"""empty message

Revision ID: 16ce73c6719a
Revises: 3e7705e80fae
Create Date: 2026-01-13 14:29:16.394479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ce73c6719a'
down_revision: Union[str, Sequence[str], None] = '3e7705e80fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autoservices', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autoservices', 'tenant_id')
    # ### end Alembic commands ###
