"""empty message

Revision ID: 4415d9ad348b
Revises: 7c4f0ffa8022
Create Date: 2026-01-13 14:34:00.165786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4415d9ad348b'
down_revision: Union[str, Sequence[str], None] = '7c4f0ffa8022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('autoservices', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'autoservices', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'autoservices', type_='foreignkey')
    op.alter_column('autoservices', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
