"""empty message

Revision ID: a549cf004b61
Revises: 0b4027945624
Create Date: 2026-01-09 18:13:08.732660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a549cf004b61'
down_revision: Union[str, Sequence[str], None] = '0b4027945624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_value', 'payment_method',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payment_value', 'autoservice',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('payment_value_autoservice_fkey'), 'payment_value', type_='foreignkey')
    op.drop_constraint(op.f('payment_value_payment_method_fkey'), 'payment_value', type_='foreignkey')
    op.create_foreign_key(None, 'payment_value', 'payment_method', ['payment_method'], ['uuid'])
    op.create_foreign_key(None, 'payment_value', 'autoservice', ['autoservice'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_value', type_='foreignkey')
    op.drop_constraint(None, 'payment_value', type_='foreignkey')
    op.create_foreign_key(op.f('payment_value_payment_method_fkey'), 'payment_value', 'payment_method', ['payment_method'], ['id'])
    op.create_foreign_key(op.f('payment_value_autoservice_fkey'), 'payment_value', 'autoservice', ['autoservice'], ['id'])
    op.alter_column('payment_value', 'autoservice',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payment_value', 'payment_method',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
